:PROPERTIES:
:ID:       10aae451-4df6-430e-8af0-8aca0e0a6c72
:END:
#+title: 001 Angler Fish

* Statement
Statement given by Nathan Watts regarding an incident near Old Fishmarket Close, a student at the University of Edinburgh. Apr 22 2012.

Watts was walking home late at night after drinking, and fell down in an alley. He rolls a cigarette, and despite being convinced he was alone, hears someone say "Can I have a cigarette?". He sees someone in complete darkness, and feels uneasy. The person is swaying and looks feverish, and repeats the question a few times. Eventually, Watts noticed that the figure's mouth wasn't moving, and that the figure was hovering above the ground. When he pulled out his phone to take a picture, the figure disappeared.

Watts came back the next day, and all he saw was an unlit Marlboro Red cigarette. A few weeks later, he sees a missing persons case for "John Fellows," who was at the same party. The photo used for Fellows shows Marlboro Red cigarettes in his pocket.

There have been six disappearances in the area, yet unsolved:
- Jessica McEwan, Nov 2005
- Sarah Baldwin, Aug 2006
- Daniel Rawlings, Dec 2006
- Ashley Dobson, May 2008
- Megan Shaw, Jun 2008
- John Fellows, Mar 2010
Dobson: sent a picture to her sister of an empty alleyway, with the text "Check out this drunk creeper, LOL!"
