:PROPERTIES:
:ID:       130acac9-a420-484f-9f98-9f097d18741b
:END:
#+title: 002 Do Not Open

* Statement
Statement of Joshua Gillespie, regarding his time and possession of an apparently empty wooden casket. Nov 22, 1998.

Gillespie goes out to explore Amsterdam, but got lost around mid afternoon. He gets back near his friends by evening, and stops in a cafe before he meets up with them. Eventually, he realizes he isn't alone: he meets "Jon", who claims to be "an Englishman in a foreign land." Gillespie is offered 10,000 pounds to take care of a package, and accepts. Jon says he'll be in touch, and leaves.

A few days later, Gillespie flies home with his friends. For nearly a year, he did not use the money given, determined to return it as soon as possible. Eventually, he uses some of it to pay for a flat. A few days later, he gets a delivery of a coffin, wrapped with a heavy metal chain and a padlock with the key still in. Three inch high letters on the padlock spelled out "DO NOT OPEN." A paper under the padlock read "Delivered with gratitude, J."

Gillespie removed the key, and moved the warm coffin into his living room, out of the way. He avoided his living room for a week, but eventually even started using it as a coffee table. One day, he placed a glass of orange juice on it. Then, Gillespie heard a soft scratching coming from inside the coffin, which stopped when he picked up the glass. He put the glass down on the other side of the coffin, and the scratching started up again over there. It stopped five minutes after he picked up the glass. One day, it started raining. Gillespie heard a moaning, almost a singing, coming from the coffin.

This scratching and moaning continued for a few months. Gillespie started occasionally waking up gasping, feeling like he couldn't breathe, and also sleepwalking. When he sleepwalked, he tended to pick up the key to the coffin and attempt to unlock it. He froze the key in a bowl of water, to prevent him from unlocking it in his sleep.

One rainy day, Gillespie notices that the coffin did not moan. Jon and two delivery men come to pick up the coffin, surprised to see him there. Gillespie gives them the key, and lets them into the living room. He hears screaming and does not investigate. The two delivery men come out /without/ Jon, and put the coffin in a van marked "Breekon and Hope deliveries".

* After Statement

Breekon and Hope was a real courier service based in Nottingham, but their records are not available.

Tim found that, for the two years that Gillespie stayed in that flat, he was the only one. The other seven flats were empty, and nobody moved in following his departure.

