:PROPERTIES:
:ID:       6b7d7e1c-3faf-4302-b8d7-6f6a68c04c3a
:END:
#+title: 003 Across The Street

* Statement
Statement of Amy Patel, regarding the alleged disappearance of her acquaintance Graham Folger. Jan 7, 2007.

Patel and Folger met in a criminology night course in Sep 2005. The two were acquaintances. In the course, Folger wrote furiously, and did not acknowledge these notes when asked about them.

One day, Patel saw Folger on a bus at night, desperately looking out the window, breathing heavily, and wiping off the window as soon as it fogged. They get off at the same stop, and walk in the same direction. Patel was pushed onto the ground, but it could not have been Folger. Folger calls an ambulance, who dismiss her quickly, and she goes to Folger's flat, right across the street from hers, to recover.

Folger's flat contains bookshelves filled with rows of identical A5 notebooks. Patel noticed a planter box which disappeared on a second look, which she says may have been because of her concussion. Folger's coffee table had a snaking pattern of lines, shifting as Patel watched, with a small square hole in the middle. Folger had found it in a secondhand shop and restored it. Folger's parents had died in a car accident, leaving him money and the flat.

Patel could see Folger's flat through her window, and she started watching him frequently. He would constantly reorder his journals, scribble in notebooks at random (even if they were full), and one time, even ate his way deliberately through a notebook. Apart from these activities, he would do nothing - smoking, staring at his table.

The weeks preceding Apr 7 had been hard for Patel, and she had left her night class. On that day, when watching Folger's flat before bed, Patel saw what looked like a long, thin arm hanging outside of his window. It pulled itself through his window, along with three other limbs that looked similar. She did not see a body or a head. As soon as it was inside, Folger's light turned off and the window closed. She told the police that she saw someone suspicious climb into a window at his address. The police rang the doorbell, and Patel saw somebody, not Folger, answer the door. This new person was wearing Folger's clothes, and the police verified this new person with his passport.

The new person looked up at Patel's flat and smiled. Over the next week, Folger's notebooks were disposed of, and not-Graham kept the curtains drawn except for when he was staring  at Patel's flat. Every picture of Folger she could find now showed this new person. A week before she moved out, she ran into not-Graham and he told her he'd have to "return the visit sometime."

* Post Statement
Tim found Patel's medical records, which suggest that she had no complications from her head trauma. Graham Folger did exist, and the testimony checks out. All photos of Folger match the description of not-Graham, except for a few Polaroids taken with his parents before their death.

One of Folger's notebooks was found, and it contains the words "keep watching" over and over.
